# databases:
#  - name: mysitedb
#    plan: free
#    databaseName: mysite
#    user: mysite

services:
  - type: web
    plan: free
    name: animebasket
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application"
envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
