# databases:
#  - name: mysitedb
#    plan: free
#    databaseName: mysite
#    user: mysite

services:
  - type: web
    plan: free
    name: animebasket
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application"
