# Generated by Django 5.1.1 on 2024-10-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('comment', models.CharField(max_length=255)),
                ('episode_id', models.CharField(max_length=255)),
            ],
        ),
    ]
